// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package observer

import (
	"sync"
)

// Ensure, that databaseMock does implement Database.
// If this is not the case, regenerate this file with moq.
var _ Database = &databaseMock{}

// databaseMock is a mock implementation of Database.
//
// 	func TestSomethingThatUsesDatabase(t *testing.T) {
//
// 		// make and configure a mocked Database
// 		mockedDatabase := &databaseMock{
// 			GetAllFunc: func() map[string][]IObserver {
// 				panic("mock out the GetAll method")
// 			},
// 			GetByObservableFunc: func(name string) ([]IObserver, error) {
// 				panic("mock out the GetByObservable method")
// 			},
// 			SetFunc: func(name string, obs IObserver) error {
// 				panic("mock out the Set method")
// 			},
// 			SetAllFunc: func(stringToIObservers map[string][]IObserver)  {
// 				panic("mock out the SetAll method")
// 			},
// 			SetObservableFunc: func(name string, observers []IObserver) error {
// 				panic("mock out the SetObservable method")
// 			},
// 		}
//
// 		// use mockedDatabase in code that requires Database
// 		// and then make assertions.
//
// 	}
type databaseMock struct {
	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() map[string][]IObserver

	// GetByObservableFunc mocks the GetByObservable method.
	GetByObservableFunc func(name string) ([]IObserver, error)

	// SetFunc mocks the Set method.
	SetFunc func(name string, obs IObserver) error

	// SetAllFunc mocks the SetAll method.
	SetAllFunc func(stringToIObservers map[string][]IObserver)

	// SetObservableFunc mocks the SetObservable method.
	SetObservableFunc func(name string, observers []IObserver) error

	// calls tracks calls to the methods.
	calls struct {
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// GetByObservable holds details about calls to the GetByObservable method.
		GetByObservable []struct {
			// Name is the name argument value.
			Name string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Name is the name argument value.
			Name string
			// Obs is the obs argument value.
			Obs IObserver
		}
		// SetAll holds details about calls to the SetAll method.
		SetAll []struct {
			// StringToIObservers is the stringToIObservers argument value.
			StringToIObservers map[string][]IObserver
		}
		// SetObservable holds details about calls to the SetObservable method.
		SetObservable []struct {
			// Name is the name argument value.
			Name string
			// Observers is the observers argument value.
			Observers []IObserver
		}
	}
	lockGetAll          sync.RWMutex
	lockGetByObservable sync.RWMutex
	lockSet             sync.RWMutex
	lockSetAll          sync.RWMutex
	lockSetObservable   sync.RWMutex
}

// GetAll calls GetAllFunc.
func (mock *databaseMock) GetAll() map[string][]IObserver {
	if mock.GetAllFunc == nil {
		panic("databaseMock.GetAllFunc: method is nil but Database.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//     len(mockedDatabase.GetAllCalls())
func (mock *databaseMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetByObservable calls GetByObservableFunc.
func (mock *databaseMock) GetByObservable(name string) ([]IObserver, error) {
	if mock.GetByObservableFunc == nil {
		panic("databaseMock.GetByObservableFunc: method is nil but Database.GetByObservable was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockGetByObservable.Lock()
	mock.calls.GetByObservable = append(mock.calls.GetByObservable, callInfo)
	mock.lockGetByObservable.Unlock()
	return mock.GetByObservableFunc(name)
}

// GetByObservableCalls gets all the calls that were made to GetByObservable.
// Check the length with:
//     len(mockedDatabase.GetByObservableCalls())
func (mock *databaseMock) GetByObservableCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockGetByObservable.RLock()
	calls = mock.calls.GetByObservable
	mock.lockGetByObservable.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *databaseMock) Set(name string, obs IObserver) error {
	if mock.SetFunc == nil {
		panic("databaseMock.SetFunc: method is nil but Database.Set was just called")
	}
	callInfo := struct {
		Name string
		Obs  IObserver
	}{
		Name: name,
		Obs:  obs,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(name, obs)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//     len(mockedDatabase.SetCalls())
func (mock *databaseMock) SetCalls() []struct {
	Name string
	Obs  IObserver
} {
	var calls []struct {
		Name string
		Obs  IObserver
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// SetAll calls SetAllFunc.
func (mock *databaseMock) SetAll(stringToIObservers map[string][]IObserver) {
	if mock.SetAllFunc == nil {
		panic("databaseMock.SetAllFunc: method is nil but Database.SetAll was just called")
	}
	callInfo := struct {
		StringToIObservers map[string][]IObserver
	}{
		StringToIObservers: stringToIObservers,
	}
	mock.lockSetAll.Lock()
	mock.calls.SetAll = append(mock.calls.SetAll, callInfo)
	mock.lockSetAll.Unlock()
	mock.SetAllFunc(stringToIObservers)
}

// SetAllCalls gets all the calls that were made to SetAll.
// Check the length with:
//     len(mockedDatabase.SetAllCalls())
func (mock *databaseMock) SetAllCalls() []struct {
	StringToIObservers map[string][]IObserver
} {
	var calls []struct {
		StringToIObservers map[string][]IObserver
	}
	mock.lockSetAll.RLock()
	calls = mock.calls.SetAll
	mock.lockSetAll.RUnlock()
	return calls
}

// SetObservable calls SetObservableFunc.
func (mock *databaseMock) SetObservable(name string, observers []IObserver) error {
	if mock.SetObservableFunc == nil {
		panic("databaseMock.SetObservableFunc: method is nil but Database.SetObservable was just called")
	}
	callInfo := struct {
		Name      string
		Observers []IObserver
	}{
		Name:      name,
		Observers: observers,
	}
	mock.lockSetObservable.Lock()
	mock.calls.SetObservable = append(mock.calls.SetObservable, callInfo)
	mock.lockSetObservable.Unlock()
	return mock.SetObservableFunc(name, observers)
}

// SetObservableCalls gets all the calls that were made to SetObservable.
// Check the length with:
//     len(mockedDatabase.SetObservableCalls())
func (mock *databaseMock) SetObservableCalls() []struct {
	Name      string
	Observers []IObserver
} {
	var calls []struct {
		Name      string
		Observers []IObserver
	}
	mock.lockSetObservable.RLock()
	calls = mock.calls.SetObservable
	mock.lockSetObservable.RUnlock()
	return calls
}
