name: Run tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17.x'
      - run: cd backend && go test -v -race ./...
